# Generated by Django 5.0.6 on 2024-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_menuitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
