# Generated by Django 5.0.6 on 2024-05-21 16:03

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.create("Managers")
    Group.objects.create("Crew")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_user_cart_customer_rename_user_order_customer_and_more"),
    ]

    operations = [migrations.RunPython(create_groups)]
