# Generated by Django 5.0.6 on 2024-05-21 19:49

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.create("Managers")
    Group.objects.create("Crew")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_category_slug"),
    ]

    operations = []
